### ISSUE TITLE
Use Steam's new official support

### ISSUE THREAD

**Issue by bgiesing** [CapitaineJSparrow/steam-repo-manager#12]
With the most recent update, there's now an official "Customization" menu in Settings to select boot videos. Any video in the `/home/deck/.steam/root/config/uioverrides/movies/` directory gets added to the list, it no longer has to be explicitly called `deck_startup.webm`.

The app should be updated to download multiple videos (and their thumbnails) to that directory under their original name. This way, you can now have multiple videos installed and shuffle between them.

**Comment by CapitaineJSparrow** [comment]
This feature is closed thanks to @jeff87218 work, update has been sent to flathub should be live in few hours
