### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Crashnoww** [CapitaineJSparrow/steam-repo-manager#3]
Here are some icons. Let me know if you'd like something modified. There are 4 icons, but I can't see them in the preview for some reason. If you can't see or get them, let me know and I'll send them in another way.

![sd bv icon v1](https://user-images.githubusercontent.com/45316646/195331612-5de9bd35-c016-490e-b2e2-35386c49878d.svg)
![sd bv icon v2](https://user-images.githubusercontent.com/45316646/195331626-c6232545-fd5b-45e5-b89d-1648f388b5f4.svg)
![sd bv icon v3](https://user-images.githubusercontent.com/45316646/195331636-0ca34647-5c87-4daa-a2d0-a3e230df02d1.svg)
![sd bv icon v4](https://user-images.githubusercontent.com/45316646/195331652-54b306b0-11dd-41be-91eb-a71e3c2e128a.svg)

**Comment by CapitaineJSparrow** [comment]
Thanks it's very appreciated ! I re upload them here as PNG so anyone can see. I really love the first. Huge work thanks man <3

![195331612-5de9bd35-c016-490e-b2e2-35386c49878d](https://user-images.githubusercontent.com/6690149/195340592-db0b989f-f400-4284-a89b-059f012d2882.png)
![195331626-c6232545-fd5b-45e5-b89d-1648f388b5f4](https://user-images.githubusercontent.com/6690149/195340595-6180c709-cf49-4615-988a-1ba6dc25cf4d.png)
![195331636-0ca34647-5c87-4daa-a2d0-a3e230df02d1](https://user-images.githubusercontent.com/6690149/195340596-7933008c-e313-4449-8d33-31c3a148b7c9.png)
![195331652-54b306b0-11dd-41be-91eb-a71e3c2e128a](https://user-images.githubusercontent.com/6690149/195340597-8d23d8e2-eee5-464c-a933-b3364fcbbde3.png)

**Comment by Crashnoww** [comment]
Anytime! Let me know if i can help in any other way.

**Comment by Crashnoww** [comment]
That's really not necessary. I'm just happy you made an awesome app!

**Comment by CapitaineJSparrow** [comment]
I pushed the update to the store (should take few hours to come live until store detect it ...) with your icons. Thanks for your work ! Unfortunately there will be a black background instead of transparent, it will be fixed in next update.

**Comment by CapitaineJSparrow** [comment]
![image](https://user-images.githubusercontent.com/6690149/195475582-f32883b4-2a03-4449-9829-36f06d2d2a33.png)

Update is now in store with new icons, thanks again !
