### ISSUE TITLE
Download File Location

### ISSUE THREAD

**Issue by n3rdcub** [CapitaineJSparrow/steam-repo-manager#8]
Does not seem to install to 3.3.2 /home/deck/.steam/root/config/uioverrides/movies/  Location. Where do files save?

**Comment by CapitaineJSparrow** [comment]
I can confirm and tested by thousand of people that videos are supposed to be saved in `/home/deck/.steam/root/config/uioverrides/movies/ `. [Related code here](https://github.com/CapitaineJSparrow/steam-repo-manager/blob/main/utils/__init__.py#L6)
