### ISSUE TITLE
[Suggestion] Option to change install folder

### ISSUE THREAD

**Issue by ArchOwlen** [CapitaineJSparrow/steam-repo-manager#9]
Steam deck's official folder is steam/root/config/uioverrides/movies/
And the current Decky Loader has a plugin that uses Home/homebrew/animations

**Comment by CapitaineJSparrow** [comment]
It is planned ! Thanks for suggestion

**Comment by moraroy** [comment]
Yes that would be good especially now that valve has made it to where we see our videos now in the customization tab in steamos

**Comment by CapitaineJSparrow** [comment]
I think this issue does not make any sense now, valve specified directory in `.steam/root/config/uioverrides/movies`, tool has been updated to put videos there and support multiple installed videos
